name: Generate Meme Index

on:
  push:
    branches:
      - memes  # Se déclenche quand on ajoute un fichier à la branche "memes"
  workflow_dispatch:  # Permet de le lancer manuellement depuis l'onglet Actions

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (Fetch all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupère toutes les branches pour éviter les erreurs

      - name: Checkout memes branch
        run: |
          git fetch origin memes  # Récupère la branche "memes"
          git checkout memes  # Bascule sur "memes"
          mkdir -p memes  # S'assure que le dossier existe
          ls -l  # Debug : Vérifie que les fichiers sont bien là

      - name: Generate meme index
        run: |
          cd memes
          echo "[" > index.json
          for file in *.jpg *.png *.gif; do
            if [ -f "$file" ]; then
              echo "  {\"name\": \"$file\", \"url\": \"https://raw.githubusercontent.com/${{ github.repository }}/memes/main/$file\"}," >> index.json
            fi
          done
          sed -i '$ s/,$//' index.json  # Supprime la dernière virgule
          echo "]" >> index.json
          mv index.json ../index.json

      - name: Commit and push index.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout memes  # Reste bien sur `memes`

          mv index.json memes/  # Déplace `index.json` dans `memes`
          git add memes/index.json
          git commit -m "Mise à jour automatique de index.json" || echo "Aucune modification à valider"
          git push origin memes  # Pousse uniquement sur `memes`
