name: Generate Meme Index
on:
  push:
    branches:
      - memes
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (Main)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Assure d'avoir accès à toutes les branches

      - name: Checkout memes branch
        run: |
          git fetch origin memes  # Récupère la branche "memes"
          git checkout memes  # Bascule sur "memes"
          mkdir -p memes  # Crée le dossier si besoin

      - name: Generate meme index
        run: |
          cd memes
          echo "[" > index.json
          for file in *.jpg *.png *.gif; do
            if [ -f "$file" ]; then
              echo "  {\"name\": \"$file\", \"url\": \"https://raw.githubusercontent.com/${{ github.repository }}/memes/main/$file\"}," >> index.json
            fi
          done
          sed -i '$ s/,$//' index.json  # Supprime la dernière virgule
          echo "]" >> index.json
          mv index.json ../index.json

      - name: Commit and push index.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          mv index.json memes/
          git add memes/index.json
          git commit -m "Mise à jour automatique de index.json" || echo "Aucune modification à valider"
          git push
