name: Generate Meme Index

on:
  push:
    branches:
      - memes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (Fetch all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout memes branch
        run: |
          git fetch origin memes
          git checkout memes
          mkdir -p memes_folder  # Rename working directory to avoid conflicts
          mv memes/* memes_folder/ 2>/dev/null || true  # Move files if they exist
          ls -l memes_folder  # Debug: Check if the files exist

      - name: Generate meme index
        run: |
          cd memes_folder
          echo "[" > index.json
          for file in *.jpg *.png *.gif *.mp3 *.ogg *.wav *.mp4 *.webm *.mkv; do
            if [ -f "$file" ]; then
              filename=$(basename -- "$file")
              title="${filename%.*}"  # Remove file extension for title
              date=$(date -r "$file" +"%Y-%m-%d %H:%M:%S")
              echo "  {" >> index.json
              echo "    \"name\": \"$filename\"," >> index.json
              echo "    \"url\": \"https://raw.githubusercontent.com/${{ github.repository }}/memes/memes_folder/$file\"," >> index.json
              echo "    \"title\": \"$title\"," >> index.json
              echo "    \"date\": \"$date\"," >> index.json
              echo "    \"hashtags\": []" >> index.json  # Placeholder for hashtags
              echo "  }," >> index.json
            fi
          done
          sed -i '$ s/,$//' index.json  # Remove last comma
          echo "]" >> index.json
          mv index.json ../index.json

      - name: Commit and push index.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          mv index.json
          git add index.json
          git commit -m "Automatic update of index.json" || echo "No changes to commit"
          git push origin main
