name: Move Uploaded Memes to memes_folder

on:
  push:
    branches:
      - main
    paths:
      - 'tmp/**'

permissions:
  contents: write

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout memes branch
        run: |
          git fetch origin memes
          git checkout memes
          mkdir -p memes_folder

      - name: Move files from tmp/ to memes_folder/
        run: |
          mv ../tmp/* memes_folder/ 2>/dev/null || echo "No files to move"

      - name: Commit and push to memes branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add memes_folder/
          git commit -m "Moved new uploads from tmp to memes_folder"
          git push origin memes

      - name: Cleanup tmp/ in main
        run: |
          git checkout main
          rm -rf tmp/*
          git add tmp/
          git commit -m "Cleaned tmp after moving files" || echo "No files to delete"
          git push origin main
